### ISSUE TITLE
Discovering candidate taxa for tree

### ISSUE THREAD

**Issue by rvosa** [naturalis/asterid-phylo-comp#1]
The steps involved probably amount roughly to:
1.  query the [taxon list](https://github.com/naturalis/asterid-phylo-comp/blob/master/data/taxa/sampling_asterids_tree.tsv), retain the records where the `include` column has a value of 1. Then, for the `names_to_query` column, take each of the comma-separated names and treat these as input for SUPERSMART.
2. for each input taxon name, perform `smrt taxize`. This will give a spreadsheet that contains all subtended species for that taxon.
3. perform `smrt align` for each of these spreadsheets. This gives a bucket of FASTA files with phylota clusters.
4. perform `smrt orthologize`, which will create superclusters from the phylota clusters.
5. perform `smrt bbmerge`, which will create a supermatrix, and a markers spreadsheet.
6. query the markers spreadsheet. There should be a column for _rbcL_ and for _matK_. Select all species that have data for these markers.
7. report these candidate species back to Frederic, who will make a selection.

**Comment by rvosa** [comment]
As of commit d922fa15d48b97f5b9d6a02d23e6606eda51d220 the results of step one and two (taxonomic name resolution) are stored. However, certain taxon names produced no matches:
- Abdulmajidia
- Brazzeia
- Careys
- Casinopsis
- Codonaceae
- Cordiaceae
- Crateranthus
- Diabelia
- Ehretiaceae
- Mydyocarpaceae
- Nyssaceae
- Oecopetalum
- Pauwloniaceae
- Pierrina
- Thomersandersiaceae
- Vesalea
- Wellsteadiaceae

**Comment by fredericlens** [comment]
Hi Rutger, 
Heb blijkbaar wat typo's gemaakt, waarvoor mijn excuses. Sommige taxa taxa mag je weglaten uit de lijst, voor anderen wil ik graag een alternatief voorstellen:
-Careys moet zijn Caryea
-Casinopsis moet zijn Cassinopsis
-Cordiaceae moet zijn Cordia
-Nyssaceae moet zijn Nyssa
-Pauwloniaceae moet zijn Paulownia
-Thomersandersiaceae moet zijn Thomandersia

Bedankt, Frederic

**Comment by rvosa** [comment]
Gecorrigeerd: c38e5aabf26ecbb1d1ca50c288df5a4691e94fd8

**Comment by rvosa** [comment]
Have run step 3 as of commit 426159675a282df394b82bd04b65c45ac8dd7b15

**Comment by rvosa** [comment]
Hi @fredericlens,

ik heb een eerste poging gedaan om dit issue van begin tot eind af te draaien op de manier zoals ik aan het begin van dit issue in gedachten had. Dat is redelijk goed gegaan, al is er nog wel wat ontbrekende data die op een andere manier binnengehaald moet worden. De resultaten zijn als volgt:
- ik heb een [tabel](../blob/master/data/markers/markers.tsv) gemaakt met alle kandidaatmarkers die zijn waargenomen door de SUPERSMART pijplijn. Onttrokken aan het zicht is de kolom met het totaal aantal soorten voor die marker: de tabel is gesorteerd in afnemend aantal soorten. Als je ergens in de tabel klikt en dan naar rechts scrollt (pijltje naar rechts op je toetsenbord) dan komt die kolom in beeld. Dit is puur om je een overzicht te geven van wat er beschikbaar is en welke markers plausibele kandidaten zijn.
- ik heb ook een [tabel](../blob/master/data/markers/taxa.tsv) gemaakt waarin per hoger taxon uit de originele boom alle soorten worden gegeven die ten minste 1 van de top zes markers uit de marker tabel hebben. "NA" betekent geen data, alle andere celwaarden zijn genbank accessie nummers.
- er zijn helaas een aantal hogere taxa waar SUPERSMART geen data voor kon vinden in genbank release 194 (dit is de versie die we hebben geindexeerd, is ongeveer een jaar oud). Daar kunnen een aantal redenen voor zijn: 
  1. er zijn uberhaupt geen soorten bekend voor dit taxon, bijvoorbeeld omdat er nog niets van is gesequenced, of omdat het hoger taxon een onbekend synoniem of foutieve spelling is.
  2. er is gewoon geen sequentie data voor de "top zes" markers in genbank release 194.
  3. de aanwezige sequentie data is niet met succes geclusterd door de [phylota](http://phylota.net) pijplijn
  4. bij monotypische genera (of genera waar genbank maar < 3 soorten voor heeft) concludeert de pijplijn dat het niet lukt om voor zo'n set soorten een fylogenetisch informatieve data set bij elkaar te zoeken, want voor minder dan drie soorten kan je geen boom bouwen.
     Die vierde, puur technische, reden is te omzeilen door met de hand (of een custom script) op zoek te gaan naar data. Hier zijn de taxa zonder data tot nu toe:
  - Aralidium: [markers](../blob/master/data/markers/taxa.tsv#L137), [species](../blob/master/data/supersmart-merged/Aralidium/species.tsv) - Reden: **monotypisch**
  - Argophyllaceae: [markers](../blob/master/data/markers/taxa.tsv#L138), [species](../blob/master/data/supersmart-merged/Argophyllaceae/species.tsv) - Reden: **geen data in GB194, wel aanwezig in recente GenBank**
  - Diabelia: [markers](../blob/master/data/markers/taxa.tsv#L277), [species](../blob/master/data/supersmart-merged/Diabelia/species.tsv) - Reden: **nul soorten herkend, wel aanwezig in recente GenBank**
  - Diervilla: [markers](../blob/master/data/markers/taxa.tsv#L278), [species](../blob/master/data/supersmart-merged/Diervilla/species.tsv) - Reden: **geen data in GB194, wel aanwezig in recente GenBank**
  - Griseliniaceae: [markers](../blob/master/data/markers/taxa.tsv#L2175), [species](../blob/master/data/supersmart-merged/Griseliniaceae/species.tsv) - Reden: **geen data in GB194, wel aanwezig in recente GenBank**
  - Heptacodium: [markers](../blob/master/data/markers/taxa.tsv#L2176), [species](../blob/master/data/supersmart-merged/Heptacodium/species.tsv) - Reden: **monotypisch**
  - Kolkwitzia: [markers](../blob/master/data/markers/taxa.tsv#L2177), [species](../blob/master/data/supersmart-merged/Kolkwitzia/species.tsv) - Reden: **monotypisch**
  - Leycesteria: [markers](../blob/master/data/markers/taxa.tsv#L2552), [species](../blob/master/data/supersmart-merged/Leycesteria/species.tsv) - Reden: **monotypisch**
  - Linnaea: [markers](../blob/master/data/markers/taxa.tsv#L2553), [species](../blob/master/data/supersmart-merged/Linnaea/species.tsv) - Reden: **monotypisch**
  - Melanophylla: [markers](../blob/master/data/markers/taxa.tsv#L2583), [species](../blob/master/data/supersmart-merged/Melanophylla/species.tsv) - Reden: **geen data in GB194, wel aanwezig in recente GenBank**
  - Napoleonaeoideae: [markers](../blob/master/data/markers/taxa.tsv#L2584), [species](../blob/master/data/supersmart-merged/Napoleonaeoideae/species.tsv) - Reden: **geen data in GB194, wel aanwezig in recente GenBank**
  - Paracryphia: [markers](../blob/master/data/markers/taxa.tsv#L2594), [species](../blob/master/data/supersmart-merged/Paracryphia/species.tsv) - Reden: **monotypisch**
  - Pennantiaceae: [markers](../blob/master/data/markers/taxa.tsv#L2595), [species](../blob/master/data/supersmart-merged/Pennantiaceae/species.tsv) - Reden: **geen data in GB194, wel aanwezig in recente GenBank**
  - Pentaphragmataceae: [markers](../blob/master/data/markers/taxa.tsv#L2596), [species](../blob/master/data/supersmart-merged/Pentaphragmataceae/species.tsv) - Reden: **monotypisch**
  - Phellinaceae: [markers](../blob/master/data/markers/taxa.tsv#L2597), [species](../blob/master/data/supersmart-merged/Phellinaceae/species.tsv) - Reden: **geen data in GB194, wel aanwezig in recente GenBank**
  - Quintinia: [markers](../blob/master/data/markers/taxa.tsv#L2598), [species](../blob/master/data/supersmart-merged/Quintinia/species.tsv) - Reden: **monotypisch**
  - Scytopetaloideae: [markers](../blob/master/data/markers/taxa.tsv#L2627), [species](../blob/master/data/supersmart-merged/Scytopetaloideae/species.tsv) - Reden: **geen data? niet compatibel met NCBI taxonomie?**
  - Torricellia: [markers](../blob/master/data/markers/taxa.tsv#L3232), [species](../blob/master/data/supersmart-merged/Torricellia/species.tsv) - Reden: **monotypisch**
  - Vesalea: [markers](../blob/master/data/markers/taxa.tsv#L3233), [species](../blob/master/data/supersmart-merged/Vesalea/species.tsv) - Reden: **nul soorten herkend, wel aanwezig in recente GenBank**

Voor vrijwel alle ontbrekende taxa is het dus zo dat het mogelijk zou moeten zijn om rechtstreeks via GenBank gericht te zoeken naar de markers die we willen hebben. De volgende stap is daarom om voor deze taxa naar de "top zes" te gaan zoeken.

**Comment by rvosa** [comment]
Inmiddels op deze subset van ontbrekende taxa de pijplijn nog een keer gedraaid. Nu ontbreken nog:
- Pentaphragmataceae
- Phellinaceae
- Vesalea
- Argophyllaceae
- Diabelia

**Comment by rvosa** [comment]
> Om alle misverstanden te vermijden: je had geschreven dat bijvoorbeeld
> Scytopetaloideae niet compatibel is met NCBI. Dit is goed mogelijk want het is
> een onderfamilie. Daarom had ik de genera toegevoegd die bij die onderfamilie
> horen: Asteranthos, Brazzeia, Crateranthus, Oubanguia, Pierrina, Rhaptopetalum,
> Scytopetalum. Heb jij de SUPERSMART pijplijn losgelaten voor elk van die genera?
> Indien ja, is Scytopetaloideae niet meer nodig als taxon en mag je het weglaten.
> Voor de de andere hogere rang taxa (onderfamilies, ordes) waarvoor ik aparte
> genera heb opgesomd geldt hetzelfde.
> 
> Bijvoorbeeld, voor Phellinaceae, probeer Phelline, het enige geslacht binnen de
> familie. Als je Phelline hebt, delete Phellinaceae. Idem voor Pentaphragmaceae,
> een familie met alleen Pentaphragma als enige geslacht. Argophyllaceae heeft
> twee genera: Argophyllum en Corokia.
> 
> Vesalea en Diabelia zijn twee geslachten die vrij recent zijn opgericht, dus ik
> kan me wel iets bij voorbeelden dat die nog niet in NCBI staan. Op zich geen
> probleem.
> 
> groeten en prettig weekend, Frederic

**Comment by rvosa** [comment]
Hi @fredericlens,

die redenatie had ik inderdaad al in overweging genomen, met als resultaat dat die genoemde vijf taxa vooralsnog niet door de pijplijn gedetecteerd worden. De rest allemaal wel. Ik zou het volgende willen voorstellen:
- voor elk hoger taxon uit de oorspronkelijke boom zetten we in eerste instantie in op drie "exemplar" soorten. Dat gaat niet voor elk taxon lukken maar voor de meeste wel. Het lijkt me goed om in ieder geval op die manier te verifieren dat deze hogere taxa in ieder geval (in grote meerderheid) netjes monofyletisch met redelijke posteriors in de boom terechtkomen.
- we doen een multilocus analyse met de volgende markers: rbcL, matK, rps16 en ndhF. Er is geen enkele marker die voor alle hogere taxa voorkomt dus we moeten een redelijke combinatie verzinnen met voldoende overlap. Met deze combinatie van vier markers zitten de meeste "exemplars" rond de drie markers met helaas wat uitschieters naar beneden, maar ik vermoed dat het voldoende is om een redelijk resultaat te krijgen.
- hier is de gereduceerde [tabel](https://github.com/naturalis/asterid-phylo-comp/blob/master/data/markers/merged.tsv) met de exemplars waar ik nu naar kijk

Aan jou nu de volgende twee vragen:
1. ben je in grote lijnen akkoord met deze selectie?
2. van de vijf nog ontbrekende hogere taxa, wil je dat ik daar nog "met de hand" sequenties bij ga zoeken?

**Comment by rvosa** [comment]
Overigens neem ik waar dat de vijf nog ontbrekende hogere taxa allemaal het scalariforme fenotype hebben dus als we uiteindelijk een comparative analysis gaan doen zijn we in feite conservatief als onze aanname is dat de transities van scalariform naar simpel gaan (dus als p<0.05 dan hebben de reviewers in ieder geval niets te zeuren als we deze vijf achterwege laten).

**Comment by fredericlens** [comment]
Hoi Rutger, 

Voor de 5 ontbrekende genera, is misschien Veselea en Diabelia het meest interesssant omdat ze tot de Dipsacales behoren, dezelfde groep waarbij ook Viburnum en Sambucus horen (Dipsacales). Deze Dipsacales boom was in het origineel mss apart opgenomen. Als je wil kijken of daar gegevens van voorhanden zijn op GenBank, zou dat super zijn. Als er geen bruikbare merkers zijn, laat ze dan gewoon weg.

Enkele bedenkingen bij de selectie van de soorten:
-Voor de sampling van de hogere taxa, is het belangrijk om systematisch soorten te selecteren. Dus geen 3 genera van dezelfde familie voor één orde, dit om aan te tonen dat gans de orde hetzelfde doorboringstype heeft (bv. er zijn 3 Ericaceae soorten geselecteerd bij ericalean lineage, terwijl er meerdere families zijn). Ideaal gezien voor bv. Cornales zouden we kunnen proberen -indien de data het toelaten- om voor elke houtige familie één 'examplar' soort eruit te filteren, dus 5 soorten voor Cornales. Dit geeft dan ook weer dat de diversere groepen iets beter vertegenwoordigd zijn in de dataset. Geen probleem indien er één of meerdere families niet vertegenwoordigd zijn.

-Voor groepen zoals de geslachten in Dipsacales, Alseuosmiaceae, Garryales, Rousseaceae is de sampling perfect. Voor andere niet-Dipsacales groepen waarvoor slechts één genus bestaat, zouden we kunnen opteren om gewoon één soort te selecteren. Bv. Griselinia lucida voor Griseliniaceae. Dat lijkt me meer dan voldoende voor deze kleine groep.

-Sommige groepen hebben iets meer variatie in vatdoorboringstype dan anderen, wat het aantal shifts kan wijzigen (ericalean lineage). Misschien moeten die groepen in de mate van het mogelijke iets denser gesampled worden zonder het aantal soorten dramatisch de hoogte in te jagen uiteraard. 

Voor de vervolgstap: zou je me de totale lijst van genera kunnen doorsturen zodat ik een voorstel voor finale selectie kan maken? 

Laat maar weten of het voor jou makkelijk is de totale taxalijst door te sturen, liefst met de merkerbeschikbaarheid, dan kan ik jou de finale selectie doorsturen. Is misschien de meest efficiente manier om vanaf hier verder te gaan. Lijkt dat jou een goed plan?

alvast bedankt voor de progress,
groeten,
Frederic

**Comment by rvosa** [comment]
Hi Frederic,

voor wat betreft de sampling heb ik de soorten binnen de hogere taxa puur gesorteerd op het aantal beschikbare merkers, dus daar kan inderdaad een grote bias in zitten. Als je een andere sampling voorstaat dan is het inderdaad het handigst als je de voorgestelde sampling spreadsheet naar eigen inzicht aanpast a.d.h. van de totale merkerlijst. Doe als volgt:
- [hier](https://github.com/naturalis/asterid-phylo-comp/blob/master/data/markers/merged.tsv) is mijn voorgestelde sampling puur gebaseerd op beschikbare data, en [daar](https://github.com/naturalis/asterid-phylo-comp/raw/master/data/markers/merged.tsv) is de niet opgemaakte versie van dezelfde spreadsheet, die je kan downloaden als tab-separated table en openen in Excel.
- [hier](https://github.com/naturalis/asterid-phylo-comp/blob/master/data/markers/taxa.tsv) is min of meer dezelfde tabel, voor reductie, en [daar](https://github.com/naturalis/asterid-phylo-comp/raw/master/data/markers/taxa.tsv) in ruwe vorm.

Als je nou de selectie aanpast in Excel (gewoon copy & paste) van de grote tabel naar de kleine en naar me terug mailt dan gebruik ik die.

Rutger

**Comment by rvosa** [comment]
De nieuwe tabel is bij commit 377405f1784c96d0fb6ef665eaa2cdd5b5892c08 toegevoegd.
